#name: Run Playwright E2E Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.52.0-noble

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache node_modules to speed up the workflow
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Install Node.js dependencies
      - name: Install dependencies
        run: npm ci

      # Run Playwright tests with HOME set to /root
      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: true
          HOME: /root

      # Upload Playwright test artifacts (e.g., reports) on failure
      - name: Upload test artifacts
        # if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
